### ISSUE TITLE
Datetime is invalid for different formats 

### ISSUE THREAD

**Issue by edvardsanta** [GuilhermeFrSaito/ToDoListApp#1]
# Summary
I tested it in a windows 10 machine in pt-br configuration, the datetime inserted on "_toDoLists" map is "dd/mm/yyyy", but when I try to select it the log says to write in "mm/dd/yyyy" format and the date is invalid in the parse.

**Comment by GuilhermeFrSaito** [comment]
Please test it when you've got time so I may know if works properly or not. Thanks!
